### ISSUE TITLE
Unity il2cpp crash bug introduced in 2021.3.12, fixed in 2021.3.16

### ISSUE THREAD

**Issue by michaelpbean** [pirunxi/il2cpp_huatuo#5]
We're encountering the following il2cpp crash bug that was introduced in Unity 2021.3.12 and fixed in 2021.3.16:
https://issuetracker.unity3d.com/issues/build-crashes-on-il2cpp-vm-class-getvirtualmethod-when-building-and-running-a-project-using-il2cpp-scripting-backend

This happens if you make a Development Build with Script Debugging enabled. The crash occurs because of a missing NULL check in the following function.
[il2cpp\libil2cpp\vm\Class.cpp:2242] il2cpp::vm::Class::GetVirtualMethod()

Unity added the NULL check back in 2031.3.16, but the latest version of Class.cpp in the il2cpp_plus repository is based on the 2021.3.14 version with the bug. Merging Unity's changes back into il2cpp_plus would be helpful.

**Comment by pirunxi** [comment]
Thanks very much! We have updated to 2020.3.43 and 2021.3.16 in main branche just now, but don't update 1.0 and DHE branche currently in consideration of stablebility.
